version: '3.8'

services:
  mavoid-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_ADMIN_PASSKEY=${VITE_ADMIN_PASSKEY}
        - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
        - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
        - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
        - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
    container_name: mavoid-portfolio
    restart: unless-stopped
    ports:
      - "3023:3000"  # Expose on port 3001 on host (change as needed)
    networks:
      - webapps

networks:
  webapps:
    driver: bridge
